PdfToImageConverter
SyncfusionExamples/WPF-PDFViewer-Examples pull request #21
Opened 2023-09-05 13:52 UTC by KrithikaGanesan

PdfToImageConverter

2023-09-13 12:17 UTC, Vikassekar requested changes

2023-09-13 15:58 UTC, KrithikaGanesan commented on PDF-to-image/Convert-PDF-page-into-image/MainWindow.xaml.cs
> +            bitmap.Save("output.png");
Yes I have modified the sample

2023-09-14 13:39 UTC, KrithikaGanesan commented on PDF-to-image/Convert-PDF-page-into-image/Convert-PDF-page-into-image.csproj
> +      <HintPath>packages\Syncfusion.PdfToImageConverter.WPF.1.0.0.2\lib\net46\Syncfusion.PdfToImageConverter.Base.dll</HintPath>
I have modified

2023-09-14 13:39 UTC, KrithikaGanesan commented on PDF-to-image/Convert-PDF-page-into-image/packages.config
> +  <package id="Syncfusion.PdfToImageConverter.WPF" version="1.0.0.2" targetFramework="net46" />
I have modified

2023-09-14 14:01 UTC, Vikassekar approved these changes

2023-09-14 14:02 UTC, merged